# Build settings

# markdown: kramdown
# permalink: pretty

port: 8000
# url: http://https://chemamora.github.io//The-Follow-Through/myblog 

include: ['_includes/header']
include: ['default']
include: ['work']
exclude: ['the_design.psd']

sass:
  sass_dir: assets/css
  style: :nested